### ISSUE TITLE
Adding "sysctl" command to the uperf client script

### ISSUE THREAD

**Issue by capolrik** [perftool-incubator/bench-uperf#60]
Following the solution found for https://issues.redhat.com/browse/RHEL-17206, TIME-WAIT should be disabled in the uperf client as it slows the creation of a new socket. In a the context of a multi-bench run, it means the system under test is not stress because the client struggle to open more connections.
It can be solve by adding  the following command at the start of the uperf-client container:
```
sysctl -w net.ipv4.tcp_tw_reuse=1 
```

**Comment by HughNhan** [comment]
The tuned params for TCP and UDP are many.  As I remember to enable a sysctl like above, it is a 3-step process;
1. create and apply a KubeletConfig to allowedUnsafeSysctls
2. Create and apply a Tuned with "net.ipv4.tcp_tw_reuse=1"
3. Annotate pod with net.ipv4.tcp_tw_reuse=1
  
"securityContext": {
      "sysctls": [
         {
            "name": "net.ipv4.tcp_tw_reuse",
            "value": "1"
         }
      ]
}

**Comment by capolrik** [comment]
Hi @HughNhan thank you for your help.
Unfortunately, when you add the security context with crucible, it is at the 'container level', to add capabilities for example. But for adding sysctls options, it is at the pod level like in this example: https://docs.openshift.com/container-platform/4.12/nodes/containers/nodes-containers-sysctls.html#nodes-containers-starting-pod-with-unsafe-sysctls_nodes-containers-using
I don't know if there is another way to add the 'sysctls' annotations.

**Comment by HughNhan** [comment]
For the record, as we spoke offline that we can use --PsecurityContext option for pod level securityContext.  Hence we can close this issue.
